{% set name = "centrally-managed-conda" %}
{% set version = "0.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/SciTools-incubator/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: fd80f8e0a6ea23be32b5c3df16f9d8bc2a01117d57a3e5a8c09f95e31801b430

build:
    number: 1002
    noarch: python
    script: {{ PYTHON }} -m pip install . -vv

requirements:
    host:
        - python >=3.6
        - pip
    run:
        - python >=3.6
        - conda-build
        - gitpython
        - conda-build-all
        - pyyaml

test:
  imports:
    - centrally_managed_conda

about:
  home: https://github.com/SciTools-incubator/centrally-managed-conda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Tools and documentation for centrally managed conda environment deployment'

extra:
  recipe-maintainers:
    - bjlittle
    - lbdreyer
    - pelson
