{% set name = "centrally-managed-conda" %}
{% set version = "0.2" %}
{% set sha256 = "fd80f8e0a6ea23be32b5c3df16f9d8bc2a01117d57a3e5a8c09f95e31801b430" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/SciTools-incubator/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - conda-build
        - gitpython
        - conda-build-all
        - pyyaml

test:
  imports:
    - centrally_managed_conda

about:
  home: https://github.com/SciTools-incubator/centrally-managed-conda
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: 'Tools and documentation for centrally managed conda environment deployment'

extra:
  recipe-maintainers:
    - bjlittle
    - lbdreyer
    - pelson
