# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GPIxZkuc7AGN9a9In6xN1UB+KMqC+nenVOMQKqzYy9sUt7HPwhxBaFg6doV/A8qZiLd90fcraruoem9mXX8NLhDiTjNdM3DBJCI/6HjTAKOjx6z8cq2vfBRFCjRFdGfb0SsFN09yfp+sFo/nTqLWBFKigVLyMppzBct6ocCU3Ygauc4FZq7UTq/VUTGLXxbXbQBp5yoLTng++JYD5s9K11fQ/H8+jA0M0UqLcmkc7K2BSuMLja45wdUQLJvWaqxBQv4neYIpyp+ZRqMl62zIMApQRb5rrlcCWEk417ZgL78ru2TFqV2GXjARXexgxbXRlG8RrX2tMI6wHrmlmXy2o9gXpf0Sqy7GtqWS2Q/hhCddj3BGv78Ykp+O5q1z8uIFGJMV7rHSCHurr4X5FfuQlD1Pl+xVrYAVHQaKN8RzXYssjl4S2v1+74HBvMOH/549Qd09SPhOqF9EOhfWOvJluFlk4vYTP0SLQkyRt6qc4Eh72qYSUkFPbfD+TVEvGDgPS44TzcdVfbytwU45YZFwq8eiZJBInMW70GlydRSfYEUAkjeMRI7hT9lJ0HZ/24IlODWxk85HTIBeV9wfSBqw35tgORaYwJhBNhY5v4PIys2hC7AogJnCB7zZ4HjjH56ExK6qbyNxrAV8x+VGOZjTFutuKa09lBS/vuJVTGCbrdA="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
