travis:
  secure:
    BINSTAR_TOKEN: TcaM4lqcpF1yaYfI+q/7xW4UmMH7VYDV9X9mqOsJt7AO/5P7PIBGsJKTi3vFpVYouM1DJYlTlLkRAfh9Yc+OiMHJ5lHtduGTWiB4wAMBCifUFcV3nHP0mdCA75Zc5IpTGEQD9lmJXFvenXAV2MGN1PCZg2RAG2hPmvuJlwU9keX89WUrEGX+liyxZf/XtPYEE9XFjnFpPbwbJBHSrDEuLG++ieqTCDkdMN5D7ZbxDQviF93rw7QUP+uCPtmI9A8JD73f7W/8M6Jj2hyuUzcpKSCXAJyl07rOc913fqPE9P3jXnZGVVijDcgLAO6JHNIUQ7sunetAH5kC6tHZVUJZE/LPkLanj4AYY1uYA7obajfz6z0bbf8hinD7oheeYDrR017huPxHjykluIq7S4jg3W0bG5nCEGfgUd579weFzWnlJl8RvEh9Tha2g6Xx6rYt7s2kQwdV20ZtdKh5lA1+UwdhsM+l3R9gZS0VEVQNOEpmSecI8Kxl+2YHXOOj7ZEkaFL7zfgpwUMp2rm33GZNyVdGL6PeNKr0rdhiLaQCxGxuX6VdNoKy9T4itJ5gy9HO6KphdpHZyCg2gT6CkesXJsr3iVKwinSPTRXAM473w6ZVM05oR78Gq3g1BW6+cXT9HXOyRo5iJI3slZ/q9JbX61lzqOt4c98EimQmANBJALY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
