travis:
  secure:
    BINSTAR_TOKEN: GPIxZkuc7AGN9a9In6xN1UB+KMqC+nenVOMQKqzYy9sUt7HPwhxBaFg6doV/A8qZiLd90fcraruoem9mXX8NLhDiTjNdM3DBJCI/6HjTAKOjx6z8cq2vfBRFCjRFdGfb0SsFN09yfp+sFo/nTqLWBFKigVLyMppzBct6ocCU3Ygauc4FZq7UTq/VUTGLXxbXbQBp5yoLTng++JYD5s9K11fQ/H8+jA0M0UqLcmkc7K2BSuMLja45wdUQLJvWaqxBQv4neYIpyp+ZRqMl62zIMApQRb5rrlcCWEk417ZgL78ru2TFqV2GXjARXexgxbXRlG8RrX2tMI6wHrmlmXy2o9gXpf0Sqy7GtqWS2Q/hhCddj3BGv78Ykp+O5q1z8uIFGJMV7rHSCHurr4X5FfuQlD1Pl+xVrYAVHQaKN8RzXYssjl4S2v1+74HBvMOH/549Qd09SPhOqF9EOhfWOvJluFlk4vYTP0SLQkyRt6qc4Eh72qYSUkFPbfD+TVEvGDgPS44TzcdVfbytwU45YZFwq8eiZJBInMW70GlydRSfYEUAkjeMRI7hT9lJ0HZ/24IlODWxk85HTIBeV9wfSBqw35tgORaYwJhBNhY5v4PIys2hC7AogJnCB7zZ4HjjH56ExK6qbyNxrAV8x+VGOZjTFutuKa09lBS/vuJVTGCbrdA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
